# sim_2024 {.doc .doc-index}

## PseudoRandom Number Generators (PRNG)

Que pondremos aca

| | |
| --- | --- |
| [multiplicative_congruential_generator](multiplicative_congruential_generator.qmd#generators.multiplicative_congruential_generator) | congruential multiplicative pseudorandom generators |
| [linear_congruential_generator](linear_congruential_generator.qmd#generators.linear_congruential_generator) | congruential linear pseudorandom generators |
| [quadratic_congrential_generator](quadratic_congrential_generator.qmd#generators.quadratic_congrential_generator) | congruential quadratic pseudorandom generators |
| [polynomial_congruential_generator](polynomial_congruential_generator.qmd#generators.polynomial_congruential_generator) | congruential polynomial pseudorandom generator |
| [multiple_congruential_generator](multiple_congruential_generator.qmd#generators.multiple_congruential_generator) | multiple congruential pseudorandom generator |
| [combined_congruential_generator](combined_congruential_generator.qmd#generators.combined_congruential_generator) | combined congruential pseudorandom generator |
| [multcombi_congruential_generator](multcombi_congruential_generator.qmd#generators.multcombi_congruential_generator) | multiple combined congruential pseudorandom generator |