# multiplicative_congruential_generator { #generators.multiplicative_congruential_generator }

`multiplicative_congruential_generator(self, **kwargs)`

congruential multiplicative pseudorandom generators

Pseudorandom generator based on the multiplicative congruential method. Initialization must be made
with keywords for all parameters.

## Other Parameters

| Name   | Type   | Description                   | Default    |
|--------|--------|-------------------------------|------------|
| `mod`  | int    | Module for residual reduction | _required_ |
| `mult` | int    | Multiplier                    | _required_ |
| `seed` | int    | initial value                 | _required_ |

## Methods

| Name | Description |
| --- | --- |
| [rand](#generators.multiplicative_congruential_generator.rand) | generation of one pseudo-random number |

### rand { #generators.multiplicative_congruential_generator.rand }

`multiplicative_congruential_generator.rand()`

generation of one pseudo-random number