# sim_2024 {.doc .doc-index}

## PseudoRandom Number Generators (PRNG)

Que pondremos aca

| | |
| --- | --- |
| [generators.multiplicative_congruential_generator](generators.multiplicative_congruential_generator.qmd#sim_2024.generators.multiplicative_congruential_generator) | congruential multiplicative pseudorandom generators |
| [generators.linear_congruential_generator](generators.linear_congruential_generator.qmd#sim_2024.generators.linear_congruential_generator) | congruential linear pseudorandom generators |
| [generators.quadratic_congrential_generator](generators.quadratic_congrential_generator.qmd#sim_2024.generators.quadratic_congrential_generator) | congruential quadratic pseudorandom generators |
| [generators.polynomial_congruential_generator](generators.polynomial_congruential_generator.qmd#sim_2024.generators.polynomial_congruential_generator) | congruential polynomial pseudorandom generator |
| [generators.multiple_congruential_generator](generators.multiple_congruential_generator.qmd#sim_2024.generators.multiple_congruential_generator) | multiple congruential pseudorandom generator |
| [generators.combined_congruential_generator](generators.combined_congruential_generator.qmd#sim_2024.generators.combined_congruential_generator) | combined congruential pseudorandom generator |
| [generators.multcombi_congruential_generator](generators.multcombi_congruential_generator.qmd#sim_2024.generators.multcombi_congruential_generator) | multiple combined congruential pseudorandom generator |

## Randomess Test

falta llenar esto

| | |
| --- | --- |
| [tests.mean_test](tests.mean_test.qmd#sim_2024.tests.mean_test) |  |
| [tests.variance_test](tests.variance_test.qmd#sim_2024.tests.variance_test) |  |