# yml file for quartodoc
project:
  type: website

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: generators
  parser: google

  sections:
    - title: PseudoRandom Congruential Generators (PRCG)
      desc: .
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - multiplicative_congruential_generator
        - linear_congruential_generator