# yml file for quartodoc
project:
  type: website

website:
  repo-url: https://github.com/
  page-navigation: true

quartodoc:
  # style of page
  style: pkgdown
  # the name used to import the package you want to create reference docs for
  package: generators
  # style of docstrings
  parser: google

  sections:
    - title: PseudoRandom Congruential Generators (PRCG)
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - multiplicative_congruential_generator
        - linear_congruential_generator
        - quadratic_congrential_generator
        - multiple_congruential_generator
        - combined_congruential_generator

format:
  html:
    theme:
      - flatly
    toc: true
    html-math-method: katex
