---
jupyter: python3
---

# sim_2024 <a href="https://github.com/DRHHugo/Simulacion-2024-II/"></a>

The pins package publishes data, models, and other Python objects, making it
easy to share them across projects and with your colleagues. You can pin
objects to a variety of pin *boards*, including folders (to share on a
networked drive or with services like DropBox), Posit Connect, Amazon
S3, and Google Cloud Storage.
Pins can be automatically versioned, making it straightforward to track changes,
re-run analyses on historical data, and undo mistakes.

## Usage

To use the pins package, you must first create a pin board. A good place
to start is [](`~pins.board_folder`), which stores pins in a directory you
specify. Here we'll use a special version of [](`~pins.board_folder`) called
[](`~pins.board_temp`) which creates a temporary board that’s automatically
deleted when your Python script or notebook session ends. This is great for examples, but
obviously you shouldn't use it for real work!

```{python}
import generators

gen = generators.multiplicative_congruential_generator(mod=2**31,mult=65539,seed=14501)
```

Above, we saved the data as a CSV, but depending on
what you’re saving and who else you want to read it, you might use the
`type` argument to instead save it as a `joblib`, `parquet`, or `json` file.

You can later retrieve the pinned data with [](`~pins.boards.BaseBoard.pin_read`):

A board on your computer is good place to start, but the real power of
pins comes when you use a board that’s shared with multiple people. To
get started, you can use [](`~pins.board_folder`) with a directory on a shared
drive or in DropBox, or if you use [Posit
Connect](https://posit.co/products/enterprise/connect/) you can use
[](`~pins.board_connect`):

You can easily control who gets to access the data using the Posit
Connect permissions pane.

The pins package also includes boards that allow you to share data on
services like Amazon’s S3 ([](`~pins.board_s3`)), Google Cloud Storage ([](`~pins.board_gcs`)),
and Azure blob storage ([](`~pins.board_azure`)).

## Contributing

- This project is released with a [Contributor Code of Conduct](https://www.contributor-covenant.org/version/2/1/CODE_OF_CONDUCT.html). By contributing to this project, you agree to abide by its terms.

- If you think you have encountered a bug, please [submit an issue](https://github.com/rstudio/pins-python/issues).