# yml file for quartodoc
project:
  type: website

website:
  title: "sim_2024"
  repo-url: https://github.com/
  page-navigation: true
  navbar:
    background: light
    pinned: true
    left:
      - text: "Get started"
        file: get_started.qmd
      - text: "Reference"
        file: reference/index.qmd
      - text: Learn more
        menu:
          - text: "Generators"
            file: generators.qmd
          - text: "Tests"
            file: tests.qmd
          - text: "Google"
            href: https://google.com
            target: _blank
    right:
      - icon: github
        href: https://github.com/rstudio/pins-python
        aria-label: Pins python GitHub
  sidebar:
    collapse-level: 1
    contents:
      - section: Main features
        contents:
          - text: "`rand`"
          - href: reference/rand.qmd
          - text: "`set_seed`"
          - href: reference/set_seed.qmd
          - text: "`random_sample`"
          - href: reference/random_sample.qmd
          - text: "`mass_function`"
          - href: reference/mass_function.qmd
          - text: "`density_function`"
          - href: reference/density_function.qmd
          - text: "`HistogramFigure`"
          - href: reference/HistogramFigure.qmd
          - text: "`PathFigure`"
          - href: reference/PathFigure.qmd
      - section: PseudoRandom Number Generators (PRNG)
        contents:
          - text: "`multiplicative_congruential_generator`"
            href: reference/generators.multiplicative_congruential_generator.qmd
          - text: "`linear_congruential_generator`"
            href: reference/generators.linear_congruential_generator.qmd
          - text: "`quadratic_congrential_generator`"
            href: reference/generators.quadratic_congrential_generator.qmd
          - text: "`polynomial_congruential_generator`"
            href: reference/generators.polynomial_congruential_generator.qmd
          - text: "`multiple_congruential_generator`"
            href: reference/generators.multiple_congruential_generator.qmd
          - text: "`combined_congruential_generator`"
            href: reference/generators.combined_congruential_generator.qmd
          - text: "`multcombi_congruential_generator`"
            href: reference/generators.multcombi_congruential_generator.qmd
      - section: Randomess Test
        contents:
          - text: "`mean test`"
            href: reference/tests.mean_test.qmd
          - text: "`variance test`"
            href: reference/tests.variance_test.qmd
      - section: Stochastic process
        contents:
          - text: "`Wiener Process`"
            href: reference/process.WienerProcess
          - text: "`Poisson Process`"
            href: reference/process.PoissonProcess
          - text: "`Compound Poisson Process`"
            href: reference/process.CompoundPoissonProcess
format:
  html:
    sidebar: true
    html-math-method: katex

quartodoc:
  title: sim_2024
  package: sim_2024
  source_dir: symlink_src
  parser: google

  sections:
    - title: Basics PseudoRandom functionalities
      desc: 'funcionalidades básicas'
      contents:
        - rand
        - set_seed
        - random_sample
        - HistogramFigure
        - process_path
        - process_sample
        - PathFigure
        - mass_function
        - density_function
    - title: PseudoRandom Number Generators (PRNG)
      desc: 'submodulo de generadores de números pseudoaleatorios'
      contents:
        - generators.multiplicative_congruential_generator
        - generators.linear_congruential_generator
        - generators.quadratic_congrential_generator
        - generators.polynomial_congruential_generator
        - generators.multiple_congruential_generator
        - generators.combined_congruential_generator
        - generators.multcombi_congruential_generator
        - generators.linear_feedback_shift_register_4
        - generators.linear_feedback_shift_register_8
        - generators.linear_feedback_shift_register_12
        - generators.linear_feedback_shift_register_16
        - generators.linear_feedback_shift_register_20
        - generators.linear_feedback_shift_register_24
    - title: Pruebas de aleatoriedad
      desc: 'submodulo de pruebas de aleatoriedad para PRNG'
      contents:
        - tests.mean_est
        - tests.mean_test
        - tests.variance_est
        - tests.variance_test
        - tests.chisq_est
        - tests.chisq_test
        - tests.series_est
        - tests.series_test
        - tests.runs_est
        - tests.runs_test
    - title: Distribuciones de probabilidad
      desc: 'submodulo de distribuciones de probabilidad'
      contents:
        - variates.Bernoulli
        - variates.Binomial
        - variates.Geometric
        - variates.NegativeBinomial
        - variates.DiscreteUniform
        - variates.Poisson
        - variates.ContinuousUniform
        - variates.Exponential
        - variates.Normal
        - variates.BoundedNormal
        - variates.RectifiedNormal
        - variates.Chisq
        - variates.Student
        - variates.Gamma
        - variates.Beta
        - variates.ExampleDis
    - title: Stochastic Process
      desc: 'submodulo de procesos estocásticos'
      contents:
        - process.WienerProcess
        - process.PoissonProcess
        - process.CompundPoissonProcess
