---
jupyter: python3
---

# sim_2024 <a href="https://github.com/DRHHugo/Simulacion-2024-II/"></a>

El paquete sim_2024 es un paquete básico de simulación estocástica construido dentro del curso *Simulación Estocástica* que se impartio en el periodo agosto-noviembre de 2024 en el programa de Acturía de la Universidad La Salle México.

## Contenido

Este paquete contiene los siguientes modulos

- *generators*: aqui se implementan algunos generadores de números pseudoaleatorios (PRNG por sus siglas en ingles) simples. Ninguno de estos generadores tiene la intención de ser utilizado más que con fines didácticos.

- *pruebas*: en este módulo se implementan algunas pruebas empíricas de aleatoriedad que son aplicables a los PRNG contenidos en el módulo *generators* así como una batería de pruebas para facilitar el análisis de muestras.

- *variates*: este modulo contiene representaciones de las variables aleatorias más utilizadas en el contexto actuarial. Esto inclute distribuciones discretas y continuas univariadas, así como las distribuciónes mutinormal y multinomial como únicos ejemplos de distribuciones multivariadas.

- *processes*: aqui se han implementado representaciones del proceso de Wiener, del proceso de Poisson homogeneo y del proceso de Poisson no-homogeneo de tasa acotada.

En toda el paquete se utilizan las definiciones y la terminología estandar de probabilidad y estadística. Para cualquier referencia sugerimos consultar la página [Wikipedia](https://es.wikipedia.org/).

## Uso

Los módulos descritos son independientes, por lo que es necesario importarlos de forma independiente. Por ejemplo, para recrear el infame PRNG *RANDU* del lenguaje Basic utilizariamos 

```{python}
import generators
RANDU = generators.multiplicative_congruential_generator(mod=2**31,mult=65539,seed=14501)
```

Cualquier generador pseudoaleatorio tiene dos métodos: *rand* y *sample*. El método *rand* se utiliza para obtener un número pseudoaleatorio, mientras que *sample* se emplea cuando se desea obtener una lista de números pseudoaleatorios.

The pins package also includes boards that allow you to share data on
services like Amazon’s S3 ([](`~pins.board_s3`)), Google Cloud Storage ([](`~pins.board_gcs`)),
and Azure blob storage ([](`~pins.board_azure`)).

## Autor

- Héctor Hugo Corrales Sánchez, hhcorrales@gmail.com.